use_frameworks!

target 'GTMotionTransitioning_Example' do
  pod 'GTMotionTransitioning', :path => '../'

  target 'GTMotionTransitioning_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
